      SUBROUTINE MATIN(J,INAME,IN,NUM1,IZ,F,R)
      DIMENSION IZ(20),F(20),S(7),DS(5),N(20),AW(20)
      CHARACTER INAME*40
C
C 'IT' IS THE VARIABLE WHICH CORRESPONDS
C TO 'IZ' IN THE SUBROUTINE MUCALC. SET IT TO 0.
C SEE LISTING OF MUCALC FOR DETAILS.
C
      IT = 0
C
C BEGIN DATA INPUT
C MATERIAL NAME
C
      WRITE(*,20)J
   20 FORMAT(1X,'ENTER NAME OF MATERIAL #',I1)
C
      READ(*,30)INAME
   30 FORMAT(A)
      DO 35 I=1,40
      IF (INAME(I:I).EQ.' '.AND.INAME(I-1:I-1).EQ.' ') THEN
      IN = I - 1
      GO TO 36
      END IF
   35 CONTINUE
   36 CONTINUE
C
C NUMBER OF COMPONENTS
C
      WRITE(*,40)J
   40 FORMAT(1X,'ENTER NUMBER OF ELEMENTS IN MATERIAL #',I1)
      READ(*,*)NUM1
C
C ATOMIC NUMBER AND MASS FRACTION
C
C SELECT INPUT MODE--MASS FRACTIONS OR CHEMICAL FORMULA
C
      WRITE(*,50)J
   50 FORMAT(1X,'FOR MATERIAL #',I1,/,
     1	     1X,'ENTER 1 TO USE ATOMIC #, MASS FRACTION PAIRS',/,
     2	     1X,'ENTER 2 TO USE CHEMICAL FORMULA')
      READ(*,*)IENTMODE
      IF (IENTMODE.EQ.2) GO TO 80
C
C INPUT ATOMIC #, MASS FRACTION PAIRS
C
      WRITE(*,60)J
   60 FORMAT(1X,'NOW ENTER VALUES FOR Z AND THE MASS FRACTION'/
     *1X,'FOR THAT Z FOR MAT. #',I1,'.  FOLLOW EACH PAIR BY A RET.')
      DO 70 I = 1,NUM1
      READ(*,*)IZ(I),F(I)
   70 CONTINUE
      GO TO 130
C
C INPUT ATOMIC #, FORMULA UNITS PAIRS
C
   80 CONTINUE
      WRITE(*,90)
   90 FORMAT(1X,'ENTER THE CHEMICAL FORMULA, IN THE FOLLOWING FORMAT:',/,
     1	     1X,'" Z, FORMULA UNITS ".',/,
     2	     1X,'FOLLOW EACH PAIR BY A CR LF.')
      DO 100 I=1,NUM1
      READ(*,*)IZ(I),N(I)
  100 CONTINUE
C
C CALCULATE SUM OF ATOMIC WEIGHTS FOR THIS COMPOUND
C
      FTOT = 0.
      DO 110 I=1,NUM1
      CALL MUCALC(IZ(I),100.,S,DS,IT)
      AW(I) = S(7)
      FTOT = FTOT + AW(I)*N(I)
  110 CONTINUE
C
C CALCULATE MASS FRACTIONS FOR EACH ELEMENT IN COMPOUND
C
      DO 120 I=1,NUM1
      F(I) = AW(I)*N(I)/FTOT
  120 CONTINUE
C
C DENSITY FROM MCMASTER FOR SINGLE ELEMENT
C OR ENTERED BY USER FOR MIXTURE
C
  130 IF (NUM1.GT.1) GO TO 140
      CALL MUCALC(IZ(1),100.,S,DS,IT)
      R = S(6)
      GO TO 160
  140 WRITE(*,150)J
  150 FORMAT(1X,'INPUT DENSITY OF MATERIAL #',I1)
      READ(*,*)R
  160 RETURN
      END
